# ============================================================
# Stage 1: deps — install node_modules
# Layer is cached by Docker until package-lock.json changes.
# ============================================================
FROM node:24-alpine AS deps
WORKDIR /app

# libc6-compat is needed by some native node addons on alpine
RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund \
    --prefer-offline \
    --fetch-retries=5 \
    --fetch-retry-maxtimeout=60000

# ============================================================
# Stage 2: builder — compile Next.js standalone output
# ============================================================
FROM node:24-alpine AS builder
WORKDIR /app

# All NEXT_PUBLIC_* vars must be declared as ARGs so Next.js
# can bake them into the static bundle at build time.
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_API_PREFIX
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_VERSION
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_APP_VERSION
ARG NEXT_PUBLIC_AUTH_ENABLED
ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_CASHFREE_API_VERSION
ARG NEXT_PUBLIC_CASHFREE_APP_ID
ARG NEXT_PUBLIC_CASHFREE_MODE
ARG NEXT_PUBLIC_CLINIC_API_URL
ARG NEXT_PUBLIC_CLINIC_ID
ARG NEXT_PUBLIC_DEBUG_BACKEND_STATUS
ARG NEXT_PUBLIC_ENABLE_ANALYTICS
ARG NEXT_PUBLIC_ENABLE_CONSOLE_LOGS
ARG NEXT_PUBLIC_ENABLE_CORS
ARG NEXT_PUBLIC_ENABLE_HTTPS
ARG NEXT_PUBLIC_ENABLE_NOTIFICATIONS
ARG NEXT_PUBLIC_ENABLE_REAL_TIME
ARG NEXT_PUBLIC_ENABLE_VIDEO_CALLS
ARG NEXT_PUBLIC_ENABLE_VIDEO_RECORDING
ARG NEXT_PUBLIC_ENABLED_PAYMENT_PROVIDERS
ARG NEXT_PUBLIC_ENVIRONMENT
ARG NEXT_PUBLIC_FACEBOOK_APP_ID
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY
ARG NEXT_PUBLIC_FRONTEND_DOMAIN
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_HEALTH_CHECK_INTERVAL
ARG NEXT_PUBLIC_LOG_LEVEL
ARG NEXT_PUBLIC_MAIN_DOMAIN
ARG NEXT_PUBLIC_PAYMENT_BRIDGE_URL
ARG NEXT_PUBLIC_RAZORPAY_KEY_ID
ARG NEXT_PUBLIC_VIDEO_NO_SHOW_ENABLED
ARG NEXT_PUBLIC_WEBSOCKET_URL
ARG NEXT_PUBLIC_WS_MAX_RECONNECT_ATTEMPTS
ARG NEXT_PUBLIC_WS_TIMEOUT
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_YOUTUBE_API_KEY
ARG NEXT_PUBLIC_APPLE_CLIENT_ID

# Expose to build environment
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL \
    NEXT_PUBLIC_API_PREFIX=$NEXT_PUBLIC_API_PREFIX \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_API_VERSION=$NEXT_PUBLIC_API_VERSION \
    NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION \
    NEXT_PUBLIC_AUTH_ENABLED=$NEXT_PUBLIC_AUTH_ENABLED \
    NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL \
    NEXT_PUBLIC_CASHFREE_API_VERSION=$NEXT_PUBLIC_CASHFREE_API_VERSION \
    NEXT_PUBLIC_CASHFREE_APP_ID=$NEXT_PUBLIC_CASHFREE_APP_ID \
    NEXT_PUBLIC_CASHFREE_MODE=$NEXT_PUBLIC_CASHFREE_MODE \
    NEXT_PUBLIC_CLINIC_API_URL=$NEXT_PUBLIC_CLINIC_API_URL \
    NEXT_PUBLIC_CLINIC_ID=$NEXT_PUBLIC_CLINIC_ID \
    NEXT_PUBLIC_DEBUG_BACKEND_STATUS=$NEXT_PUBLIC_DEBUG_BACKEND_STATUS \
    NEXT_PUBLIC_ENABLE_ANALYTICS=$NEXT_PUBLIC_ENABLE_ANALYTICS \
    NEXT_PUBLIC_ENABLE_CONSOLE_LOGS=$NEXT_PUBLIC_ENABLE_CONSOLE_LOGS \
    NEXT_PUBLIC_ENABLE_CORS=$NEXT_PUBLIC_ENABLE_CORS \
    NEXT_PUBLIC_ENABLE_HTTPS=$NEXT_PUBLIC_ENABLE_HTTPS \
    NEXT_PUBLIC_ENABLE_NOTIFICATIONS=$NEXT_PUBLIC_ENABLE_NOTIFICATIONS \
    NEXT_PUBLIC_ENABLE_REAL_TIME=$NEXT_PUBLIC_ENABLE_REAL_TIME \
    NEXT_PUBLIC_ENABLE_VIDEO_CALLS=$NEXT_PUBLIC_ENABLE_VIDEO_CALLS \
    NEXT_PUBLIC_ENABLE_VIDEO_RECORDING=$NEXT_PUBLIC_ENABLE_VIDEO_RECORDING \
    NEXT_PUBLIC_ENABLED_PAYMENT_PROVIDERS=$NEXT_PUBLIC_ENABLED_PAYMENT_PROVIDERS \
    NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT \
    NEXT_PUBLIC_FACEBOOK_APP_ID=$NEXT_PUBLIC_FACEBOOK_APP_ID \
    NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY \
    NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID \
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
    NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID \
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
    NEXT_PUBLIC_FIREBASE_VAPID_KEY=$NEXT_PUBLIC_FIREBASE_VAPID_KEY \
    NEXT_PUBLIC_FRONTEND_DOMAIN=$NEXT_PUBLIC_FRONTEND_DOMAIN \
    NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID \
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY \
    NEXT_PUBLIC_HEALTH_CHECK_INTERVAL=$NEXT_PUBLIC_HEALTH_CHECK_INTERVAL \
    NEXT_PUBLIC_LOG_LEVEL=$NEXT_PUBLIC_LOG_LEVEL \
    NEXT_PUBLIC_MAIN_DOMAIN=$NEXT_PUBLIC_MAIN_DOMAIN \
    NEXT_PUBLIC_PAYMENT_BRIDGE_URL=$NEXT_PUBLIC_PAYMENT_BRIDGE_URL \
    NEXT_PUBLIC_RAZORPAY_KEY_ID=$NEXT_PUBLIC_RAZORPAY_KEY_ID \
    NEXT_PUBLIC_VIDEO_NO_SHOW_ENABLED=$NEXT_PUBLIC_VIDEO_NO_SHOW_ENABLED \
    NEXT_PUBLIC_WEBSOCKET_URL=$NEXT_PUBLIC_WEBSOCKET_URL \
    NEXT_PUBLIC_WS_MAX_RECONNECT_ATTEMPTS=$NEXT_PUBLIC_WS_MAX_RECONNECT_ATTEMPTS \
    NEXT_PUBLIC_WS_TIMEOUT=$NEXT_PUBLIC_WS_TIMEOUT \
    NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL \
    NEXT_PUBLIC_YOUTUBE_API_KEY=$NEXT_PUBLIC_YOUTUBE_API_KEY \
    NEXT_PUBLIC_APPLE_CLIENT_ID=$NEXT_PUBLIC_APPLE_CLIENT_ID \
    NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build:deploy

# ============================================================
# Stage 3: runner — minimal production image (~200MB vs ~1GB)
# ============================================================
FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup -g 1001 -S nodejs \
    && adduser -S nextjs -u 1001

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
